load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "telemetry_core",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "telemetry_core",
    edition = "2024",
    visibility = ["//visibility:public"],
)

rust_test(
    name = "telemetry_core_test",
    crate = ":telemetry_core",
    edition = "2024",
)
