load("@rules_python//python:py_binary.bzl", "py_binary")
load("@rules_python//python:py_test.bzl", "py_test")

py_binary(
    name = "sync",
    srcs = ["sync_versions.py"],
    imports = ["tools/version"],
    main = "sync_versions.py",
    python_version = "3.12",
    visibility = ["//visibility:public"],
)

py_test(
    name = "version_consistency_test",
    srcs = [
        "sync_versions.py",
        "sync_versions_test.py",
    ],
    imports = ["tools/version"],
    main = "sync_versions_test.py",
    data = [
        "//:Cargo.toml",
        "//:MODULE.bazel",
    ],
    python_version = "3.12",
)

exports_files(["sync_versions.py"])
