load("@crates//:defs.bzl", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_binary")

rust_binary(
    name = "prismo",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    deps = all_crate_deps(normal = True) + [
        "//crates/core:core",
        "//crates/plugin-host:plugin_host",
        "//plugins/example-rust:example_rust",
        "//crates/tui:tui",
    ],
    visibility = ["//visibility:public"],
)

sh_test(
    name = "cpp_smoke_test",
    srcs = ["smoke_test.sh"],
    args = [
        "$(rlocationpath :prismo)",
        "$(rlocationpath //plugins/example-cpp:example_cpp)",
    ],
    data = [
        ":prismo",
        "//plugins/example-cpp:example_cpp",
        "@bazel_tools//tools/bash/runfiles",
    ],
)
