[package]
name = "prismo"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
crossterm.workspace = true
ratatui.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
prismo-core = { path = "../../crates/core" }
prismo-example-rust = { path = "../../plugins/example-rust" }
prismo-tui = { path = "../../crates/tui" }
