load("@crates//:defs.bzl", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_binary")

exports_files(["prismo-plugin.toml"])

rust_binary(
    name = "example_rust",
    srcs = ["src/main.rs"],
    edition = "2024",
    deps = all_crate_deps(normal = True) + [
        "//crates/plugin-protocol:plugin_protocol",
        "//crates/plugin-sdk/rust:plugin_sdk_rust",
    ],
    visibility = ["//visibility:public"],
)
