[package]
name = "prismo-example-rust"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "example_rust"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
rand.workspace = true
serde.workspace = true
prismo-plugin-protocol = { path = "../../crates/plugin-protocol" }
prismo-plugin-sdk-rust = { path = "../../crates/plugin-sdk/rust" }
