load("@prismo_crates//:defs.bzl", "all_crate_deps")
load("@rules_rs//rs:rust_binary.bzl", "rust_binary")
load("//bazel:defs.bzl", "prismo_bundle")

rust_binary(
    name = "prismo",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    deps = all_crate_deps(normal = True, cargo_only = True) + [
        "//crates/core:core",
        "//crates/plugin-host:plugin_host",
        "//crates/tui:tui",
    ],
    visibility = ["//visibility:public"],
)

prismo_bundle(
    name = "example_prismo",
    prismo = ":prismo",
    plugins = [
        "//plugins/example-cpp:example_cpp_plugin",
        "//plugins/example-rust:example_rust_plugin",
    ],
    visibility = ["//visibility:public"],
)
