load("@prismo_crates//:defs.bzl", "all_crate_deps")
load("@rules_rs//rs:rust_library.bzl", "rust_library")

rust_library(
    name = "tui",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "prismo_tui",
    edition = "2024",
    rustc_env = {
        "PRISMO_VERSION": "0.1.3",
    },
    deps = all_crate_deps(normal = True, cargo_only = True) + [
        "//crates/core:core",
    ],
    visibility = ["//visibility:public"],
)
