load("@rules_cc//cc:defs.bzl", "cc_binary")
load("//bazel:defs.bzl", "prismo_plugin")

exports_files(["prismo-plugin.toml"])

cc_binary(
    name = "example_cpp",
    srcs = ["src/main.cc"],
    copts = ["-std=c++17"],
    visibility = ["//visibility:public"],
    deps = [
        "//crates/plugin-sdk/cpp:cpp_sdk",
    ],
)

prismo_plugin(
    name = "example_cpp_plugin",
    executable = ":example_cpp",
    manifest = ":prismo-plugin.toml",
    visibility = ["//visibility:public"],
)
