load("@crates//:defs.bzl", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_binary")

rust_binary(
    name = "homepage_demo",
    srcs = ["src/main.rs"],
    edition = "2024",
    deps = all_crate_deps(normal = True) + [
        "//crates/core:core",
        "//crates/tui:tui",
        "//plugins/example-rust:example_rust_lib",
    ],
    visibility = ["//visibility:public"],
)
