load("@npm//website:prettier/package_json.bzl", prettier_bin = "bin")
load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

config_setting(
    name = "host_linux_aarch64",
    constraint_values = [
        "@platforms//cpu:aarch64",
        "@platforms//os:linux",
    ],
)

config_setting(
    name = "host_linux_x86_64",
    constraint_values = [
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
    ],
)

config_setting(
    name = "host_macos_aarch64",
    constraint_values = [
        "@platforms//cpu:aarch64",
        "@platforms//os:macos",
    ],
)

config_setting(
    name = "host_macos_x86_64",
    constraint_values = [
        "@platforms//cpu:x86_64",
        "@platforms//os:macos",
    ],
)

sh_binary(
    name = "rustfmt",
    srcs = ["rustfmt.sh"],
    args = select({
        ":host_linux_aarch64": ["$(rootpath @@rules_rs++toolchains+rustfmt_linux_aarch64_1_85_0//:rustfmt_bin)"],
        ":host_linux_x86_64": ["$(rootpath @@rules_rs++toolchains+rustfmt_linux_x86_64_1_85_0//:rustfmt_bin)"],
        ":host_macos_aarch64": ["$(rootpath @@rules_rs++toolchains+rustfmt_macos_aarch64_1_85_0//:rustfmt_bin)"],
        ":host_macos_x86_64": ["$(rootpath @@rules_rs++toolchains+rustfmt_macos_x86_64_1_85_0//:rustfmt_bin)"],
        "//conditions:default": ["$(rootpath @@rules_rs++toolchains+rustfmt_macos_aarch64_1_85_0//:rustfmt_bin)"],
    }),
    data = select({
        ":host_linux_aarch64": ["@@rules_rs++toolchains+rustfmt_linux_aarch64_1_85_0//:rustfmt_bin"],
        ":host_linux_x86_64": ["@@rules_rs++toolchains+rustfmt_linux_x86_64_1_85_0//:rustfmt_bin"],
        ":host_macos_aarch64": ["@@rules_rs++toolchains+rustfmt_macos_aarch64_1_85_0//:rustfmt_bin"],
        ":host_macos_x86_64": ["@@rules_rs++toolchains+rustfmt_macos_x86_64_1_85_0//:rustfmt_bin"],
        "//conditions:default": ["@@rules_rs++toolchains+rustfmt_macos_aarch64_1_85_0//:rustfmt_bin"],
    }),
    visibility = ["//visibility:public"],
)

alias(
    name = "buildifier",
    actual = "@buildifier_prebuilt//:buildifier",
    visibility = ["//visibility:public"],
)

sh_binary(
    name = "clang_format",
    srcs = ["clang_format.sh"],
    args = select({
        ":host_linux_aarch64": ["$(rootpath @clang_format_linux_aarch64//:clang_format/data/bin/clang-format)"],
        ":host_linux_x86_64": ["$(rootpath @clang_format_linux_x86_64//:clang_format/data/bin/clang-format)"],
        ":host_macos_aarch64": ["$(rootpath @clang_format_macos_aarch64//:clang_format/data/bin/clang-format)"],
        ":host_macos_x86_64": ["$(rootpath @clang_format_macos_x86_64//:clang_format/data/bin/clang-format)"],
        "//conditions:default": ["$(rootpath @clang_format_macos_aarch64//:clang_format/data/bin/clang-format)"],
    }),
    data = select({
        ":host_linux_aarch64": ["@clang_format_linux_aarch64//:clang_format/data/bin/clang-format"],
        ":host_linux_x86_64": ["@clang_format_linux_x86_64//:clang_format/data/bin/clang-format"],
        ":host_macos_aarch64": ["@clang_format_macos_aarch64//:clang_format/data/bin/clang-format"],
        ":host_macos_x86_64": ["@clang_format_macos_x86_64//:clang_format/data/bin/clang-format"],
        "//conditions:default": ["@clang_format_macos_aarch64//:clang_format/data/bin/clang-format"],
    }),
    visibility = ["//visibility:public"],
)

prettier_bin.prettier_binary(
    name = "prettier",
    visibility = ["//visibility:public"],
)
