name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v6

      - name: Set Up Bazel
        uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
          cache-save: ${{ github.event_name != 'pull_request' }}

      - name: Bazel Build
        run: bazel build //...

      - name: Bazel Test
        run: bazel test //...
